<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- FIXME: this should be a NuGet package -->
  <ItemGroup>
    <Reference Include="MelonLoader">
        <HintPath>$(TribeNineRoot)\MelonLoader\net6\MelonLoader.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>