name: build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    environment:
      name: MYENV

    steps:
    - uses: actions/checkout@v4

    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Setup Nim
      uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: '2.2.10'

    - name: Get Meson
      run: pip install meson

    - name: Meson setup
      run: meson setup build -Dwarning_level=3 -Dbuildtype=release

    - name: Meson build
      run: meson compile -C build -v

    - name: Meson install
      run: python install.py build tnz-${{ github.ref_name }}-x64

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: tnz-${{ github.ref_name }}-x64
        path: tnz-${{ github.ref_name }}-x64
        if-no-files-found: error