name: build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Setup Nim
      uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: '2.2.4'

    - name: Meson install
      uses: BSFishy/meson-build@v1.0.3
      with:
        meson-version: 1.8.1
        action: install
        setup-options: -Dwarning_level=3
        options: --destdir=tnz-x64

    - name: Upload Release
      uses: actions/upload-artifact@v4
      with:
        name: tnz-x64
        path: build/tnz-x64
